DROP FOREIGN TABLE IF EXISTS DAMAGE_TYPE_FT;
DROP FOREIGN TABLE IF EXISTS LORE_DEFINITION_FT;

DROP USER MAPPING IF EXISTS FOR POSTGRES SERVER SOURCE_DB;
DROP SERVER IF EXISTS SOURCE_DB CASCADE;
DROP EXTENSION IF EXISTS POSTGRES_FDW;